[build]
  publish = "dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[functions."stats"]
  netlify_blobs = ["fluffhaven-stats"]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200